apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  namespace: micro-auth
spec:
  replicas: 1
  selector: { matchLabels: { app: web-frontend } }
  template:
    metadata: { labels: { app: web-frontend } }
    spec:
      containers:
        - name: web-frontend
          image: vipinde/web-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  namespace: micro-auth
spec:
  selector: { app: web-frontend }
  ports:
    - port: 80
      targetPort: 80
  type: NodePort

